Revert debugs

diff --git a/.github/workflows/nodejs.yml b/.github/workflows/nodejs.yml
--- a/.github/workflows/nodejs.yml
+++ b/.github/workflows/nodejs.yml
@@ -36,6 +36,168 @@ jobs:
           name: build
           path: dist
 
+  lint:
+    name: Run linter using Node 14.x
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-node@v2
+        with:
+          node-version: "14.x"
+      - name: npm ci
+        run: npm ci
+      - name: npm run eslint
+        run: npm run eslint
+      - name: test-types
+        run: npm run test-types
+
+  test:
+    name: Test Unit using Node ${{ matrix.node-version }}
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        node-version: [12.x, 14.x]
+    env:
+      TEST_REPEATS: 5
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-node@v2
+        with:
+          node-version: ${{ matrix.node-version }}
+      - name: npm ci
+        run: npm ci
+      - name: test-unit
+        timeout-minutes: 7
+        run: npm run test-unit
+
+  integration:
+    name: ${{ matrix.test-name }} ${{ matrix.websocket-url.name }} using Node ${{ matrix.node-version }}
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        node-version: [12.x, 14.x]
+        test-name: [
+            "test-integration-no-resend",
+            "test-integration-resend",
+            "test-integration-dataunions",
+        ]
+        websocket-url:
+            - name: "default"
+              url:  ""
+            - name: "storage-node-only"
+              url:  "ws://localhost:8890/api/v1/ws"
+
+        exclude:
+          # no need to test different ws urls for dataunion tests
+          - test-name: "test-integration-dataunions"
+            websocket-url:
+                - name: "storage-node-only"
+                - url:  "ws://localhost:8890/api/v1/ws"
+    env:
+      TEST_NAME: ${{ matrix.test-name }}
+      WEBSOCKET_URL: ${{ matrix.websocket-url.url}}
+      TEST_REPEATS: 2
+
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-node@v2
+        with:
+          node-version: ${{ matrix.node-version }}
+      - name: npm ci
+        run: npm ci
+      - name: Start Streamr Docker Stack
+        uses: streamr-dev/streamr-docker-dev-action@v1.0.0-alpha.3
+        with:
+          services-to-start: "mysql redis engine-and-editor cassandra parity-node0 parity-sidechain-node0 bridge broker-node-storage-1 nginx smtp"
+      - name: Run Test
+        run: npm run $TEST_NAME
+
+  flakey:
+    name: Flakey Tests using Node ${{ matrix.node-version }}
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        node-version: [12.x, 14.x]
+
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-node@v2
+        with:
+          node-version: ${{ matrix.node-version }}
+      - name: npm ci
+        run: npm ci
+      - name: Start Streamr Docker Stack
+        uses: streamr-dev/streamr-docker-dev-action@v1.0.0-alpha.3
+        with:
+          services-to-start: "mysql redis engine-and-editor cassandra parity-node0 parity-sidechain-node0 bridge broker-node-storage-1 nginx smtp"
+      - uses: nick-invision/retry@v2
+        name: Run Test
+        with:
+          max_attempts: 2
+          timeout_minutes: 15
+          retry_on: error
+          command: npm run test-flakey || echo "::warning::Flakey Tests Failed"
+
+  browser:
+    name: Test Browser using Node 14.x
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-node@v2
+        with:
+          node-version: "14.x"
+      - uses: actions/download-artifact@v2
+        with:
+          name: build
+          path: dist
+      - name: npm ci
+        run: npm ci
+      - name: Start Streamr Docker Stack
+        uses: streamr-dev/streamr-docker-dev-action@v1.0.0-alpha.3
+        with:
+          services-to-start: "mysql redis engine-and-editor cassandra parity-node0 parity-sidechain-node0 bridge broker-node-storage-1 nginx smtp"
+
+      - uses: nick-invision/retry@v2
+        name: Run Test
+        with:
+          max_attempts: 3
+          timeout_minutes: 3
+          retry_on: error
+          command: npm run test-browser
+
+  benchmarks:
+    name: Test Benchmark using Node ${{ matrix.node-version }}
+    runs-on: ubuntu-latest
+    needs: build
+
+    strategy:
+      matrix:
+        node-version: [12.x, 14.x]
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-node@v2
+        with:
+          node-version: ${{ matrix.node-version }}
+      - uses: actions/download-artifact@v2
+        with:
+          name: build
+          path: dist
+      - name: Start Streamr Docker Stack
+        uses: streamr-dev/streamr-docker-dev-action@v1.0.0-alpha.3
+        with:
+          services-to-start: "mysql redis engine-and-editor cassandra parity-node0 parity-sidechain-node0 bridge broker-node-storage-1 nginx smtp"
+      - name: npm ci
+        run: npm ci
+      - name: benchmarks
+        run: npm run benchmarks > benchmarks.txt
+      - uses: actions/upload-artifact@v2
+        with:
+          name: benchmarks
+          path: benchmarks.txt
+
   streamr-client-testing-tool:
     name: ${{ matrix.config-name }} ${{ matrix.test-name }}
     needs: build
@@ -82,16 +244,12 @@ jobs:
         with:
           repository: streamr-dev/streamr-client-testing
           path: streamr-client-testing
-      - uses: actions/setup-java@v1
-        with:
-          java-version: '8'
       - name: setup-client-testing
         working-directory: streamr-client-testing
         run: |
           ## npm install is used because package-lock.json could be from a previous client version.
           npm install
           npm link streamr-client
-          java -version
           ./gradlew fatjar
       - name: run-client-testing
         timeout-minutes: 10
