Prevent flakey dataunion server tests from failing build.

diff --git a/.github/workflows/nodejs.yml b/.github/workflows/nodejs.yml
--- a/.github/workflows/nodejs.yml
+++ b/.github/workflows/nodejs.yml
@@ -92,6 +92,9 @@ jobs:
       - name: test-flakey
         run: npm run test-flakey || echo "::warning::Flakey Tests Failed" && true
 
+      - name: test-flakey
+        run: npm run test-flakey || echo "::warning::Flakey Tests Failed" && true
+
   streamr-client-testing-tool:
     needs: [test, lint]
     runs-on: ubuntu-latest
